[package]
name = "garfutils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"
image = "0.24.7"

comic-format = { path = "../comic-format" }
